- name: Setup Tomcat
  hosts: all
  become: yes

  tasks:

    - name: Download tomcat from dlcdn
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.35/bin/apache-tomcat-10.1.35.tar.gz"
        dest: "/root/apache-tomcat-10.1.35.tar.gz"

    - name: Untar the apache file
      command: tar -zxvf /root/apache-tomcat-10.1.35.tar.gz -C /root/
      args:
        creates: /root/apache-tomcat-10.1.35

    - name: Rename the tomcat directory
      command: mv /root/apache-tomcat-10.1.35 /root/tomcat
      args:
        creates: /root/tomcat

    - name: Install Java (Amazon Corretto 17)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Setting the context.xml file
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: Create Tomcat systemd Service File
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          User=root
          Group=root
          Type=forking
          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_HOME=/root/tomcat"
          ExecStart=/root/tomcat/bin/startup.sh
          ExecStop=/root/tomcat/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start tomcat Service
      service:
        name: tomcat
        state: started
        enabled: yes
